### ISSUE TITLE
Error due to invalid ui5 specVersion even with current ui5 tooling installed

### ISSUE THREAD

**Issue by js1972** [c-kobo/ui5con2023#9]
Hi, I'm trying to work through this amazing tutorial but am stuck.
I hav a BAS dev space and have cloned the (starter) repo. I then use the fiori generator to add the custom fiori app. Now when I try cds watch (app preview) it fails with these errors:
```
ValidationError: Invalid ui5.yaml configuration for project managetravels

Unsupported "specVersion"

/home/user/projects/ui5con2023/app/managetravels/ui5.yaml:1

1: specVersion: "3.1"
   ^
Your UI5 CLI installation might be outdated.
Supported specification versions: "3.0", "2.6", "2.5", "2.4", "2.3", "2.2", "2.1", "2.0", "1.1", "1.0", "0.1"
For details, see: https://sap.github.io/ui5-tooling/pages/Configuration/#specification-versions
    at Validator.validate (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/validation/validator.js:61:10)
    at async _validate (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/validation/validator.js:91:2)
    at async validate (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/validation/validator.js:114:2)
    at async file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/Module.js:349:6
    at async Promise.all (index 0)
    at async Module._readConfigFile (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/Module.js:345:29)
    at async Module._getYamlConfigurations (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/Module.js:273:19)
    at async Module._getConfigurations (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/Module.js:209:21)
    at async Module._getSpecifications (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/Module.js:125:17)
    at async projectGraphBuilder (file:///home/user/projects/ui5con2023/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:118:61) {
  project: { id: 'managetravels' },
  yaml: {
    path: '/home/user/projects/ui5con2023/app/managetravels/ui5.yaml',
    source: 'specVersion: "3.1"\n' +
      'metadata:\n' +
      '  name: sap.fe.cap.managetravels\n' +
      'type: application\n' +
      'server:\n' +
      '  customMiddleware:\n' +
      '    - name: fiori-tools-appreload\n' +
      '      afterMiddleware: compression\n' +
      '    - name: ui5-tooling-transpile-middleware\n' +
      '      afterMiddleware: compression\n' +
      '      configuration:\n' +
      '        debug: true\n' +
      '        excludePatterns:\n' +
      '          - /Component-preload.js\n' +
      'builder:\n' +
      '  customTasks:\n' +
      '    - name: ui5-tooling-transpile-task\n' +
      '      afterTask: replaceVersion\n' +
      '      configuration:\n' +
      '        debug: true\n',
    documentIndex: 0
  },
  errors: [
    {
      keyword: 'errorMessage',
      dataPath: '/specVersion',
      schemaPath: '#/properties/specVersion/errorMessage',
      params: {
        errors: [
          {
            keyword: 'enum',
            dataPath: '/specVersion',
            schemaPath: '#/properties/specVersion/enum',
            params: [Object],
            message: 'should be equal to one of the allowed values'
          }
        ]
      },
      message: 'Unsupported "specVersion"\n' +
        'Your UI5 CLI installation might be outdated.\n' +
        'Supported specification versions: "3.0", "2.6", "2.5", "2.4", "2.3", "2.2", "2.1", "2.0", "1.1", "1.0", "0.1"\n' +
        'For details, see: https://sap.github.io/ui5-tooling/pages/Configuration/#specification-versions'
    }
  ]
}
```

I have the latest ui5 tooling installed locally within the project and globally:

```
user: ui5con2023 $ ui5 -v
INFO: Using local @ui5/cli installation

3.6.1 (from /home/user/projects/ui5con2023/node_modules/@ui5/cli/bin/ui5.cjs)
user: ui5con2023 $ npm -g ls
/home/user/.node_modules_global/lib
└── @ui5/cli@3.6.1
```

Any ideas?

**Comment by c-kobo** [comment]
Hi @js1972 Jason,

thank you for your feedback!
I could reproduce this issue and will adress it to the Fiori tools colleagues.
As a mitigation, please change the specVersion in file app/managetravels/ui5.yaml to specVersion: "3.0"

Best regards
Christian

**Comment by js1972** [comment]
Thanks Christian. Will carry on with spec version 3.0 but I do recall
reading somewhere that the typescript stuff needed 3.1 ?!?  Let’s see how
it goes. ;-)

**Comment by c-kobo** [comment]
Ji @js1972, TypeScript support was already in place with specVersion 2.6.
The Fiori tools colleagues meanwhile confirmed the issue with the invalid version 3.1 and are investigating on this.
If the proposed mitigation solved this for you, I would kindly ask you to close this issue.

**Comment by js1972** [comment]
Dropping the spec version back does indeed solve the issue. Thank you!
